CREATE TABLE USERS (
  ID SERIAL PRIMARY KEY,
  USERNAME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  PROFILE_PHOTO_URL VARCHAR(255),
  BIOGRAPHY VARCHAR(100),
  TIMEZONE VARCHAR(50),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

CREATE TABLE POSTS (
  ID SERIAL PRIMARY KEY,
  USER_ID INT REFERENCES USERS(ID),
  TEXT_CONTENT TEXT,
  IMAGE_URL VARCHAR(255),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

CREATE TABLE FOLLOWS (
  ID SERIAL PRIMARY KEY,
  FOLLOWER_ID INT REFERENCES USERS(ID),
  FOLLOWEE_ID INT REFERENCES USERS(ID),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MESSAGES (
  ID SERIAL PRIMARY KEY,
  SENDER_ID INT REFERENCES USERS(ID),
  RECEIVER_ID INT REFERENCES USERS(ID),
  MESSAGE_CONTENT TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COMMENTS (
  ID SERIAL PRIMARY KEY,
  USER_ID INT REFERENCES USERS(ID),
  POST_ID INT REFERENCES POSTS(ID),
  PARENT_COMMENT_ID INT REFERENCES COMMENTS(ID),
  TEXT_CONTENT TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

CREATE TABLE POST_LIKES (
  ID SERIAL PRIMARY KEY,
  USER_ID INT REFERENCES USERS(ID),
  POST_ID INT REFERENCES POSTS(ID),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE POST_DISLIKES (
  ID SERIAL PRIMARY KEY,
  USER_ID INT REFERENCES USERS(ID),
  POST_ID INT REFERENCES POSTS(ID),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COMMENT_LIKES (
  ID SERIAL PRIMARY KEY,
  USER_ID INT REFERENCES USERS(ID),
  COMMENT_ID INT REFERENCES COMMENTS(ID),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COMMENT_DISLIKES (
  ID SERIAL PRIMARY KEY,
  USER_ID INT REFERENCES USERS(ID),
  COMMENT_ID INT REFERENCES COMMENTS(ID),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);